### ISSUE TITLE
phpmyadmin

### ISSUE THREAD

**Issue by noahmistry** [benlumia007/sturdy-docker#3]
Hello,

This isn't really a issue more so that I need some guidance on how to configure phpmyadmin web gui for the sturdy-docker. I know the docs mention that phpmyadmin is already included in the custom.yml resources section but i'm not sure if i have to configure it for web gui or is that already done.

Please advise

Thank you

**Comment by benlumia007** [comment]
I'm closing this ticket for now. If you still have issues, you can reopen.
